package bidwin.database;

import bidwin.models.Bid;
import bidwin.models.Product;
import cz.zcu.kiv.server.sqlite.UserAlreadyExistsException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class QueryBid {
    private static Log logger = LogFactory.getLog(QueryBid.class);

    public static Bid addBid(Bid bid) throws SQLException{

        Connection connection = null;
        PreparedStatement preparedStatement = null;
        try {
            connection = mysqlDB.getInstance().connect();
            preparedStatement =
                    connection.prepareStatement("INSERT INTO `bidwin`.`bids`(`order_id`,`price`,`retailer_email`)VALUES(?,?,?)",
                            Statement.RETURN_GENERATED_KEYS);

            preparedStatement.setLong(1, bid.getOrderId());
            preparedStatement.setDouble(2, bid.getPrice());
            preparedStatement.setString(3,bid.getRetailerEmail());
            preparedStatement.executeUpdate();

            ResultSet tableKeys = preparedStatement.getGeneratedKeys();
            tableKeys.next();
            long autoGeneratedID = tableKeys.getLong(1);
            bid.setId(autoGeneratedID);
            return bid;
        } finally {
            if (preparedStatement != null) {
                try {
                    preparedStatement.close();
                } catch (SQLException e1) {
                    logger.error(e1);
                }
            }
            if (connection != null) {
                try {
                    connection.close();
                } catch (SQLException e1) {
                    logger.error(e1);
                }
            }
        }

    }

    public static Bid getWinningBid(long orderId) {
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        try {
            connection = mysqlDB.getInstance().connect();
            preparedStatement =
                    connection.prepareStatement("SELECT * FROM bids WHERE order_id=? order by `timestamp` DESC limit 1;");
            preparedStatement.setLong(1,orderId);


            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                Bid bid = new Bid();
                bid.setId(resultSet.getLong("id"));
                bid.setOrderId(resultSet.getLong("order_id"));
                bid.setPrice(resultSet.getDouble("price"));
                bid.setRetailerEmail(resultSet.getString("retailer_email"));
                return bid;
            }
            return null;

        } catch (SQLException e) {
            logger.error(e);
            return null;
        } finally {
            if (preparedStatement != null) {
                try {
                    preparedStatement.close();
                } catch (SQLException e1) {
                    logger.error(e1);
                }
            }
            if (connection != null) {
                try {
                    connection.close();
                } catch (SQLException e1) {
                    logger.error(e1);
                }
            }

        }

    }


    public static void main(String[] args) {
        Bid bid = new Bid();
        bid.setOrderId(123);
        bid.setPrice(400);
        try {
            addBid(bid);
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }
}